# @file
# .travis.yml - Drupal 8 Travis CI Integration

language: php

sudo: false

php:
  - 5.6
  - 7.0

env:
  global:
    - MODULE_NAME='block_user_info'
    - DRUPAL_REPO='git://git.drupal.org/project/drupal.git'
    - DRUPAL_VERSION='8.2.x'
    - PHPCS_VERSION='2.7.*'
    - CODER_VERSION='8.2.9'
    - SEPARATOR='========================================'

#notifications:
#  slack: 'xxx'

# Cache Composer & Drush directories.
cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - echo $SEPARATOR
  - echo "Before install"
  - echo $SEPARATOR

  # Disable xdebug.
  # - phpenv config-rm xdebug.ini

  # Composer.
  # - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  # - source $HOME/.bashrc
  # - composer self-update

  # Drush.
  # - composer global require drush/drush:~8.1

  # Codesniffer.
  # - composer global require squizlabs/php_codesniffer:$PHPCS_VERSION

  # Coder.
  # - composer global require drupal/coder:$CODER_VERSION
  # - ln -s ~/.composer/vendor/drupal/coder/coder_sniffer/Drupal ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/

  # Ensure the PHP environment is ready.
  # - phpenv rehash

install:
  - echo $SEPARATOR
  - echo "Install"
  - echo $SEPARATOR

before_script:
  - echo $SEPARATOR
  - echo "Before script"
  - echo $SEPARATOR

script:
  - echo $SEPARATOR
  - echo "Script"
  - echo $SEPARATOR
